export const DND_ACTIVATE = 'dnd-activate'
export const DND_DEACTIVATE = 'dnd-deactivate'
export const DND_TOGGLE = 'dnd-toggle'
export const REQUEST_STATUS = 'request-status'
export const CURRENT_STATUS = 'current-status'
export const MSG_CHANGE = 'msg-change'
export const DURATION_CHANGE = 'duration-change'
export const SLACK_TOKEN_CHANGE = 'slack-token-change'